version: '3.8'
services:
  ed-training-audio:
    image: some.registry.com/xr2learn-enablers/ed-training-audio:latest
    build:
      context: 'Supervised_Training/Supervised_Audio_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Supervised_Training/Supervised_Audio_Modality:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "./configuration.json:/app/configuration.json"
    working_dir: /app
    environment:
      - KEY=${KEY}
    #    entrypoint: /bin/sh -c
    command: python supervised_audio_modality/train.py

  ed-training-body-tracking:
    image: some.registry.com/xr2learn-enablers/ed-training-body-tracking:latest
    #    runtime: nvidia
    build:
      context: 'Supervised_Training/Supervised_Body_Tracking_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Supervised_Training/Supervised_Body_Tracking_Modality:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "./configuration.json:/app/configuration.json"
    working_dir: /app
    environment:
      - KEY=${KEY}
    #    entrypoint: /bin/sh -c
    command: python supervised_body_tracking_modality/train.py

  ssl-audio:
    image: some.registry.com/xr2learn-enablers/ssl-audio:latest
    #    runtime: nvidia
    build:
      context: 'SSL_Training/SSL_Audio_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./SSL_Training/SSL_Audio_Modality:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "./configuration.json:/app/configuration.json"
    working_dir: /app
    environment:
      # To include environment variables in the format below
      - KEY=${KEY}
    #    entrypoint: /bin/sh -c
    command: python ssl_audio_modality/pre_train.py

  pre-processing-audio:
    image: some.registry.com/xr2learn-enablers/pre-processing-audio:latest
    build:
      context: 'Pre_processing/Pre_processing_Audio_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Pre_processing/Pre_processing_Audio_Modality:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "./configuration.json:/app/configuration.json"
    working_dir: /app
    environment:
      # To include environment variables in the format below
      - KEY=${KEY}
    #    entrypoint: /bin/sh -c
    command: python pre_processing_audio_modality/preprocess.py

  ssl-features-generation-audio:
    image: some.registry.com/xr2learn-enablers/ssl-features-generation-audio:latest
    build:
      context: 'SSL_Features_Extraction/SSL_Features_Extraction_Audio_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./SSL_Features_Extraction/SSL_Features_Extraction_Audio_Modality:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "./configuration.json:/app/configuration.json"
    working_dir: /app
    environment:
      # To include environment variables in the format below
      - KEY=${KEY}
    #    entrypoint: /bin/sh -c
    command: python ssl_features_extraction_audio_modality/generate_features.py

  handcrafted-features-generation-audio:
    image: some.registry.com/xr2learn-enablers/handcrafted-features-generation-audio:latest
    build:
      context: 'Handcrafted_Features_Extraction/Handcrafted_Features_Extraction_Audio_modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Handcrafted_Features_Extraction/Handcrafted_Features_Extraction_Audio_modality:/app"
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "./configuration.json:/app/configuration.json"
    working_dir: /app
    environment:
      # To include environment variables in the format below
      - KEY=${KEY}
    #    entrypoint: /bin/sh -c
    command: python handcrafted_features_extraction_audio_modality/generate_features.py