version: '3'
services:
  ed-training-audio:
    image: some.registry.com/xr2learn-enablers/ed-training-audio:latest
    #    runtime: nvidia
    build:
      context: 'Supervised_Training/Supervised_Audio_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Supervised_Training/Supervised_Audio_Modality:/app"
    working_dir: /app
    environment:
      - KEY=${KEY}
  #    entrypoint: /bin/sh -c

  ssl-audio:
    image: some.registry.com/xr2learn-enablers/ssl-audio:latest
    #    runtime: nvidia
    build:
      context: 'SSL_Training/SSL_Audio_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./SSL_Training/SSL_Audio_Modality:/app"
    #      - "./configuration.json:/app/configuration.json"
    working_dir: /app
    environment:
      # To include environment variables in the format below
      - KEY=${KEY}
    #    entrypoint: /bin/sh -c
    command: python ssl_audio_modality/pre_train.py

  pre-processing-audio:
    image: some.registry.com/xr2learn-enablers/pre-processing-audio:latest
    build:
      context: 'Pre_processing/Pre_processing_Audio_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Pre_processing/Pre_processing_Audio_Modality:/app"
    working_dir: /app
    environment:
      # To include environment variables in the format below
      - KEY=${KEY}
    #    entrypoint: /bin/sh -c
    command: python pre_processing_audio_modality/preprocess.py

  ssl-features-generation-audio:
    image: some.registry.com/xr2learn-enablers/ssl-features-generation-audio:latest
    build:
      context: 'SSL_Features_Extraction/SSL_Features_Extraction_Audio_Modality'
      dockerfile: 'Dockerfile'
    volumes:
      - "./SSL_Features_Extraction/SSL_Features_Extraction_Audio_Modality:/app"
    working_dir: /app
    environment:
      # To include environment variables in the format below
      - KEY=${KEY}
    #    entrypoint: /bin/sh -c
    command: python ssl_features_extraction_audio_modality/generate_features.py