name: Python package

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pre-processing/Pre_processing_Audio_Modality -- Install dependencies and run tests
      working-directory: ./Pre_processing/Pre_processing_Audio_Modality
      run: |
        pip install -r requirements.txt
        python -m unittest discover -s tests
    - name: Handcrafted_Features_Extraction/Handcrafted_Features_Extraction_Audio_modality -- Install dependencies and run tests
      working-directory: ./Handcrafted_Features_Extraction/Handcrafted_Features_Extraction_Audio_modality
      run: |
        pip install -r requirements.txt
        python -m unittest discover -s tests
    - name: SSL_Features_Extraction/SSL_Features_Extraction_Audio_Modality -- Install dependencies and run tests
      working-directory: ./SSL_Features_Extraction/SSL_Features_Extraction_Audio_Modality
      run: |
        pip install -r requirements.txt
        python -m unittest discover -s tests
    - name: SSL_Training/SSL_Audio_Modality -- Install dependencies and run tests
      working-directory: ./SSL_Training/SSL_Audio_Modality
      run: |
        pip install -r requirements.txt
        python -m unittest discover -s tests
    - name: Supervised_Training/Supervised_Audio_Modality -- Install dependencies and run tests
      working-directory: ./Supervised_Training/Supervised_Audio_Modality
      run: |
        pip install -r requirements.txt
        python -m unittest discover -s tests
